import Head from "next/head";
import Chart from "chart.js";
import Countrygraph from "@/components/Countrygraph";
import Endyeargraph from "@/components/Endyeargraph";
import Sectorgraph from "@/components/Sectorgraph";
import Topicgraph from "@/components/Topicgraph";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Countrygraph data={data} />
          <Endyeargraph data={data} />
          <Sectorgraph data={data} />
          <Topicgraph data={data} />
        </main>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3000/api");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
